// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Niwa.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Niwa.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240507081649_AddedNavigationFieldForNoteRevision")]
    partial class AddedNavigationFieldForNoteRevision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollectionNote", b =>
                {
                    b.Property<Guid>("CollectionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotesId")
                        .HasColumnType("uuid");

                    b.HasKey("CollectionsId", "NotesId");

                    b.HasIndex("NotesId");

                    b.ToTable("CollectionNote");
                });

            modelBuilder.Entity("GardenNote", b =>
                {
                    b.Property<Guid>("FeaturedNotesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Garden1Id")
                        .HasColumnType("uuid");

                    b.HasKey("FeaturedNotesId", "Garden1Id");

                    b.HasIndex("Garden1Id");

                    b.ToTable("GardenNote");
                });

            modelBuilder.Entity("GardenUser", b =>
                {
                    b.Property<Guid>("SubscribedGardensId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscribersId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscribedGardensId", "SubscribersId");

                    b.HasIndex("SubscribersId");

                    b.ToTable("GardenUser");
                });

            modelBuilder.Entity("Niwa.Models.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Niwa.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Niwa.Models.Garden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("Niwa.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Access")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<Guid>("LatestRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GardenId");

                    b.HasIndex("LatestRevisionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Niwa.Models.NoteFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteFiles");
                });

            modelBuilder.Entity("Niwa.Models.NoteRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Access")
                        .HasColumnType("integer");

                    b.Property<string>("ContentDelta")
                        .HasColumnType("text");

                    b.Property<bool>("ContentRewritten")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SummaryDelta")
                        .HasColumnType("text");

                    b.Property<bool>("SummaryRewritten")
                        .HasColumnType("boolean");

                    b.Property<string>("TitleDelta")
                        .HasColumnType("text");

                    b.Property<bool>("TitleRewritten")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PreviousRevisionId")
                        .IsUnique();

                    b.ToTable("NoteRevisions");
                });

            modelBuilder.Entity("Niwa.Models.NoteTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("Niwa.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "viewer"
                        },
                        new
                        {
                            Id = 2,
                            Label = "editor"
                        },
                        new
                        {
                            Id = 3,
                            Label = "commentator"
                        });
                });

            modelBuilder.Entity("Niwa.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaf91a62-1964-46c6-ab36-a95af1486272"),
                            CreatedDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "BLbHwG7Eui2aV4IzvzZcR9IZc57kw9BUrJt9RPMhkYU=;w3ecK1DTNBsZbf5R1hQgDw==",
                            UpdatedDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("NoteUser", b =>
                {
                    b.Property<Guid>("SubscribedNotesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscribersId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscribedNotesId", "SubscribersId");

                    b.HasIndex("SubscribersId");

                    b.ToTable("NoteUser");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("CollectionNote", b =>
                {
                    b.HasOne("Niwa.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("NotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GardenNote", b =>
                {
                    b.HasOne("Niwa.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("FeaturedNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.Garden", null)
                        .WithMany()
                        .HasForeignKey("Garden1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GardenUser", b =>
                {
                    b.HasOne("Niwa.Models.Garden", null)
                        .WithMany()
                        .HasForeignKey("SubscribedGardensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubscribersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Niwa.Models.Collection", b =>
                {
                    b.HasOne("Niwa.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Niwa.Models.Comment", b =>
                {
                    b.HasOne("Niwa.Models.Note", "Note")
                        .WithMany("Comments")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.Comment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Niwa.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Niwa.Models.Garden", b =>
                {
                    b.HasOne("Niwa.Models.User", "User")
                        .WithMany("Gardens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Niwa.Models.Note", b =>
                {
                    b.HasOne("Niwa.Models.Garden", "Garden")
                        .WithMany("Notes")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.NoteRevision", "LatestRevision")
                        .WithOne("Note")
                        .HasForeignKey("Niwa.Models.Note", "LatestRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("LatestRevision");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Niwa.Models.NoteFile", b =>
                {
                    b.HasOne("Niwa.Models.Note", "Note")
                        .WithMany("Files")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Niwa.Models.NoteRevision", b =>
                {
                    b.HasOne("Niwa.Models.NoteRevision", "PreviousRevision")
                        .WithOne()
                        .HasForeignKey("Niwa.Models.NoteRevision", "PreviousRevisionId");

                    b.Navigation("PreviousRevision");
                });

            modelBuilder.Entity("Niwa.Models.NoteTag", b =>
                {
                    b.HasOne("Niwa.Models.Note", "Note")
                        .WithMany("Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("NoteUser", b =>
                {
                    b.HasOne("Niwa.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("SubscribedNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubscribersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Niwa.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niwa.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Niwa.Models.Garden", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Niwa.Models.Note", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Niwa.Models.NoteRevision", b =>
                {
                    b.Navigation("Note")
                        .IsRequired();
                });

            modelBuilder.Entity("Niwa.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Gardens");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
