<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Niwa.Database\Niwa.Database.csproj"/>
        <ProjectReference Include="..\Niwa.Models\Niwa.Models.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="UnitsOfWork\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FossilDelta" Version="0.1.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1"/>
        <PackageReference Include="Sqids" Version="3.1.0"/>
    </ItemGroup>

</Project>
