<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Niwa.Models\Niwa.Models.csproj"/>
        <ProjectReference Include="..\Niwa.Repositories\Niwa.Repositories.csproj"/>
    </ItemGroup>

</Project>
